import localFont from "next/font/local";
import "./globals.css";
import "./css/weather/css/weather-icons.min.css";
import "./css/weather/css/weather-icons-wind.min.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function RootLayout({ children }) {
  return (
    <html lang={"en"}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased hydrated`}
      >
        <Navbar />
        <main className="max-w-[85rem] w-full mx-auto px-4 my-24">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}

export default RootLayout;
